name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-linux:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [Linux, Windows, Mac]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        os-dep: [sudo apt install libxcursor-dev, echo, echo]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        ${{ matrix.os-dep }} |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
      
